Change Config.java to Enable SlimeFun-side Optimization
TheBusyBiscuit/CS-CoreLib pull request #38
Opened 2018-02-24 15:57 UTC by creator3

SlimeFun  does this a few times in `BlockStorage`
```java
new Config("data-storage/Slimefun/temp.yml");
```
Unfortunately, this still incurs the cost of opening a file. On my server, I'm running a version of SlimeFun that has a special subclass of Config that isn't backed by a `FileConfiguration`. Adding this constructor allows me to call
```java
super( (File) null, (FileConfiguration) null);
```
and avoid loading a .yml. I've overridden any methods that could cause a NullPointerException. This seems to have helped performance (like CargoNets), so I'm trying to PR it, and this is the first step. I accidentally ran an autoformatter, but I think I've gotten the diff back down to something reasonable. There is one spot I had to change "§" to "\u00a7" because I didn't want to deal with figuring out the correct encoding.

On the SlimeFun side, I have some questions that I'll just ask here.
First, is there a reason the tempfile is saved [on this line](https://github.com/TheBusyBiscuit/Slimefun4/blob/1d0660db535cbefc87ec1d5dd5863c450401ed3b/src/me/mrCookieSlime/Slimefun/api/BlockStorage.java#L229)? Second, is [this call](https://github.com/TheBusyBiscuit/Slimefun4/blob/1d0660db535cbefc87ec1d5dd5863c450401ed3b/src/me/mrCookieSlime/Slimefun/api/BlockStorage.java#L370) to `_integrated_removeBlockInfo` necessary? The reason I ask is because it isn't called in
```java
void setBlockInfo(Block b, String json, boolean updateTicker) 
```

Third, is it okay to cache the parsed string data?
```java
Map<Location, String> storage
```
would become
```java
Map<Location, Map_Str_Str_Config> storage
```
Or it could be cached but done lazily if you think doing all the parsing at startup would be too much.

Finally, can my memory-only Config be backed by a Map<String, String> and not support any of the more complex types supported by the regular Config? The current [parseJSON](https://github.com/TheBusyBiscuit/Slimefun4/blob/1d0660db535cbefc87ec1d5dd5863c450401ed3b/src/me/mrCookieSlime/Slimefun/api/BlockStorage.java#L299) is like this, and it seems best to keep similar behavior.

2018-02-24 16:18 UTC, TheBusyBiscuit commented
Do not update the version in the pom.xml.
This is done automatically when a version is released.

2018-02-24 16:22 UTC, TheBusyBiscuit requested changes

2018-02-24 16:22 UTC, TheBusyBiscuit commented on src/me/mrCookieSlime/CSCoreLibPlugin/Configuration/Config.java
> +					im.setDisplayName("\u00a7r" + this.getString(path + "_extra.custom-skullOwner") + "'s Head");
Use ChatColor.translateAlternateColorCodes('&', ...) instead.

2018-02-24 16:22 UTC, TheBusyBiscuit commented on pom.xml
> +    <version>1.5.17</version>
Do not change this manually.

2018-02-24 16:22 UTC, TheBusyBiscuit commented on src/me/mrCookieSlime/CSCoreLibPlugin/Configuration/Config.java
> +	protected void setSimpleValue(String path, Object value) {
Just name it "store" ? Sounds better in my opinion.

2018-02-24 16:27 UTC, TheBusyBiscuit commented
@creator3 
"First, is there a reason the tempfile is saved on this line?"
Yes, because it isn't a temporary file, it's the chunks.sfc file.

"Second, is this call to _integrated_removeBlockInfo necessary?"
I honestly do not know, it's been years since I wrote this. Someone needs to do some research and testing.

And about your ideas, try what works best for yourself, no need to ask for permission on any change you want to make. I will intervene if a Pull Request has flaws and request changes.

2018-02-24 18:03 UTC, creator3 commented
Thanks, I didn't notice that it was cfg.save(**chunks**).

As far as I can tell, _integrated_removeBlockInfo isn't necessary because the same values will be written over with the new data anyway. I don't think removing it has broken anything on my server yet.

I've undone the version change, renamed the method to "store", and replace "\u00a7r" with ChatColor.RESET.

2018-02-25 07:42 UTC, TheBusyBiscuit approved these changes

2018-02-25 08:18 UTC, merged